### ISSUE TITLE
Chrome interpolation of capes

### ISSUE THREAD

**Issue by Nektro** [dries007/Dries007.net#3]
Removing the interpolation of images in chrome requires the following
```css
img {
    image-rendering: pixelated;
}
```
